STORYNAMES = [
    "Vacations",
    "Principal for a Day",
    "Santa Claus Coming",
    "Valentines",
    "Lunchroom",
    "Halloween Monsters",
    "Special Mother",
    "Twas Night Before",
    "Birthday",
    "All About Me",
    "Bakery",
    "Mountain Hike",
    "Summer Camp",
    "Silly Summer Goals",
    "Baltimore Trip",
    "Baby Advice",
    "Bike Riding",
    "Pretty Princess",
]